var quizLessonBoth = "lesson";var lessonNumber = 39;var numOfAllQuiz = 40;var lessonTitle = "Personalpronomen: Nominativ - Part III (Nominative personal pronouns)";var btnColor = ["#F30101","#5F0000","#FFC400","#BB0A00"];var quesToRemove = [];var startNarration = [];var narration = ["Er = He","Sie = She","Es = It (replaces neuter nouns)","Es = It (in impersonal situations)","Sie = They",""];var forTitles = ["Er","Sie","Es","Es","Sie"];var engTitles = ["He","She","It (neuter)","It (impersonal)","They"];var forSideTitles = forTitles;var engSideTitles = ["He","She","It (neuter pronoun)","It (impersonal)","They"];var titleSkip = [false,false,false,false,false];var exampleNums = [3,3,2,6,4];var forExamples = ["<strong>Er</strong> mag sein brandneues Fahrrad.","<strong>Er</strong> ist für ein Kind sehr intelligent.","<strong>Er</strong> ist der Vorsitzende der Firma.","<strong>Sie</strong> fährt mit dem Bus zur Arbeit.","<strong>Sie</strong> spielt sehr gut Klavier.","<strong>Sie</strong> ist eine wichtige Führungsperson im Staat.","Wo ist <em>das Auto</em>? <strong>Es</strong> ist in der Garage.","<em>Das Buch</em> ist blau. <strong>Es</strong> ist blau.","<strong>Es</strong> schneit.","<strong>Es</strong> macht viel Spaß, hier zu laufen.","<strong>Es</strong> hat mir geschmeckt!","<strong>Es</strong> ist schwierig, auf das Eis zu klettern.","Wie spät ist <strong>es</strong>?","<strong>Es</strong> war zu kalt, um das Haus zu verlassen.","<strong>Sie</strong> lernen viele interessante Sachen in der Schule.","<strong>Sie</strong> sind Studenten an der Universität.","<strong>Sie</strong> beschlossen, mit dem Zug zu fahren","<strong>Sie</strong> wollten zu Hause einen Film schauen."];var engExamples = ["<em>He</em> likes his brand new bike.","<em>He</em> is very smart for a child.","<em>He</em> is the president of the company.","<em>She</em> takes the bus to go to work.","<em>She</em> plays the piano very well.","<em>She</em> is an important leader in the country.","Where is <em>the car</em>? <em>It</em> is in the garage. (replaces the neuter noun)","<em>The book</em> is blue. <em>It</em> is blue. (replaces the neuter noun)","<em>It</em> is snowing","<em>It</em> is a lot of fun to run here.","<em>It</em> tasted good (to me)!","<em>It</em> is difficult to climb on the ice.","What time is <em>it</em>?","<em>It</em> was too cold to leave the house.","<em>They</em> learn a lot of interesting things at school.","<em>They</em> are university students.","<em>They</em> decided to travel by train.","<em>They</em> wanted to watch a movie at home."];


var forExtra1 = ["<strong>Er</strong> ist nicht zu Hause.","<strong>Er</strong> weiß es noch nicht.","<strong>Er</strong> kann sehr weit sehen.","<strong>Er</strong> fährt viel zu schnell!","<strong>Er</strong> arbeitet morgen nicht.","<strong>Er</strong> hat ein sehr gutes Gedächtnis.","<strong>Er</strong> hat zwanzig Minuten gewartet.","<strong>Er</strong> ist nicht so ängstlich wie ich."];var engExtra1 = ["<em>He</em> is not at home.","<em>He</em> does not know yet.","<em>He</em> can see very far.","<em>He</em> is going way too fast!","<em>He</em> doesn't work tomorrow.","<em>He</em> has a very good memory.","<em>He</em> waited for twenty minutes.","<em>He</em> is not as scared as I (am)."];var imageExtra1 = ["../../block/63/images/pic2.jpg","../../block/66/images/pic4.jpg","../../vocab/39/images/pic7.jpg","../../verb/10/images/pic6.jpg","../../vocab/36/images/pic11.jpg","../../vocab/90/images/pic4.jpg","../../verb/112/images/pic3.jpg","../../block/77/images/pic5.jpg"];var fastExtra1 = ["../../block/63/sounds/sound3","../../block/66/sounds/sound7","../../vocab/39/sounds/sound27","../../verb/10/sounds/sound23","../../vocab/36/sounds/sound43","../../vocab/90/sounds/sound13","../../verb/112/sounds/sound11","../../block/77/sounds/sound9"];var slowExtra1 = ["../../block/63/sounds/sound4","../../block/66/sounds/sound8","../../vocab/39/sounds/sound28","../../verb/10/sounds/sound24","../../vocab/36/sounds/sound44","../../vocab/90/sounds/sound14","../../verb/112/sounds/sound12","../../block/77/sounds/sound10"];

var forExtra2 = ["<strong>Sie</strong> bezahlt für mich.","<strong>Sie</strong> fährt ein blaues Auto.","<strong>Sie</strong> reist gerne allein.","<strong>Sie</strong> kann sehr hoch springen.","<strong>Sie</strong> hat einen neuen Laptop.","<strong>Sie</strong> wählt den grünen Stift.","<strong>Sie</strong> hat sich an etwas erinnert.","<strong>Sie</strong> sah Vögel am Himmel.","<strong>Sie</strong> muss den Bericht schreiben.","<strong>Sie</strong> hat eine schöne Stimme.","<strong>Sie</strong> hat fünf Jahre lang getanzt."];var engExtra2 = ["<em>She</em> is paying for me.","<em>She</em> drives a blue car.","<em>She</em> likes to travel alone.","<em>She</em> can jump very high.","<em>She</em> has a new laptop computer.","<em>She</em> chooses the green pencil.","<em>She</em> remembered something.","<em>She</em> was seeing birds in the sky.","<em>She</em> must write the report.","<em>She</em> has a beautiful voice.","<em>She</em> danced for five years."];var imageExtra2 = ["../../verb/81/images/pic2.jpg","../../block/3/images/pic3.jpg","../../vocab/93/images/pic7.jpg","../../verb/19/images/pic7.jpg","../../verb/4/images/pic7.jpg","../../verb/39/images/pic2.jpg","../../verb/85/images/pic3.jpg","../../verb/91/images/pic4.jpg","../../verb/16/images/pic7.jpg","../../vocab/87/images/pic12.jpg","../../verb/45/images/pic3.jpg"];var fastExtra2 = ["../../verb/81/sounds/sound7","../../block/3/sounds/sound5","../../vocab/93/sounds/sound27","../../verb/19/sounds/sound27","../../verb/4/sounds/sound27","../../verb/39/sounds/sound7","../../verb/85/sounds/sound11","../../verb/91/sounds/sound15","../../verb/16/sounds/sound27","../../vocab/87/sounds/sound35","../../verb/45/sounds/sound11"];var slowExtra2 = ["../../verb/81/sounds/sound8","../../block/3/sounds/sound6","../../vocab/93/sounds/sound28","../../verb/19/sounds/sound28","../../verb/4/sounds/sound28","../../verb/39/sounds/sound8","../../verb/85/sounds/sound12","../../verb/91/sounds/sound16","../../verb/16/sounds/sound28","../../vocab/87/sounds/sound36","../../verb/45/sounds/sound12"];


var forExtra4 = ["<strong>Es</strong> regnet selten hier.","<strong>Es</strong> dauert zwischen drei und fünf Tagen.","<strong>Es</strong> ist wichtig, dass du verstehst.","Sie können hier bleiben, <strong>es</strong> ist sehr spät.","<strong>Es</strong> regnete draußen; allerdings hatten sie trotzdem eine gute Zeit."];
var engExtra4 = ["<em>It</em> rarely rains here.","<em>It</em> takes between three and five days.","<em>It</em> is important that you understand.","You can stay here, <em>it</em> is very late.","<em>It</em> was raining outside; however, they still had a good time."];
var imageExtra4 = ["../../vocab/37/images/pic7.jpg","../../convo/images/convo18A.jpg","../../block/17/images/pic14.jpg","../../verb/19/images/pic12.jpg","../../block/104/images/pic5.jpg"];
var fastExtra4 = ["../../vocab/37/sounds/sound27","../../convo/18/sounds/1fast9","../../block/17/sounds/sound27","../../verb/19/sounds/sound47","../../block/104/sounds/sound9"];
var slowExtra4 = ["../../vocab/37/sounds/sound28","../../convo/18/sounds/1slow9","../../block/17/sounds/sound28","../../verb/19/sounds/sound48","../../block/104/sounds/sound10"];


var forExtra5 = ["<strong>Sie</strong> verlassen die Schule um halb vier.","<strong>Sie</strong> werden einen neuen Welpen annehmen.","<strong>Sie</strong> sind bereit, ein neues Haus zu haben.","<strong>Sie</strong> gingen Kanufahren auf dem Fluss.","<strong>Sie</strong> waren glücklich, die Show zu sehen.","<strong>Sie</strong> spielen mit gefälschten Pistolen.","<strong>Sie</strong> durften neue Kleider kaufen.","<strong>Sie</strong> sprachen über ihr Wochenende."];
var engExtra5 = ["<em>They</em> leave school at half past three.","<em>They</em> will adopt a new puppy.","<em>They</em> are ready to have a new house.","<em>They</em> used to go canoeing in the river.","<em>They</em> were happy to see the show.","<em>They</em> are playing with fake guns.","<em>They</em> were allowed to purchase new clothes.","<em>They</em> were talking about their weekend."];
var imageExtra5 = ["../../verb/69/images/pic2.jpg","../../verb/150/images/pic6.jpg","../../verb/4/images/pic1.jpg","../../verb/8/images/pic5.jpg","../../block/85/images/pic1.jpg","../../vocab/93/images/pic12.jpg","../../verb/29/images/pic6.jpg","../../verb/104/images/pic4.jpg"];
var fastExtra5 = ["../../verb/69/sounds/sound7","../../verb/150/sounds/sound23","../../verb/4/sounds/sound3","../../verb/8/sounds/sound19","../../block/85/sounds/sound1","../../vocab/93/sounds/sound47","../../verb/29/sounds/sound23","../../verb/104/sounds/sound15"];
var slowExtra5 = ["../../verb/69/sounds/sound8","../../verb/150/sounds/sound24","../../verb/4/sounds/sound4","../../verb/8/sounds/sound20","../../block/85/sounds/sound2","../../vocab/93/sounds/sound48","../../verb/29/sounds/sound24","../../verb/104/sounds/sound16"];


