var quizLessonBoth = "both";var lessonNumber = 9;var numOfAllQuiz = 9;var lessonTitle = "Bestimmte Artikel (Definite articles)";var btnColor = ["#1EEC00","#163F00","#90E700","#254800"];var quesToRemove = [];var startNarration = ["In English, the definite article ''the'' is used everywhere; it doesn't matter if the word is plural, masculine or feminine.","In German however, there are several singular definite articles, depending on the gender, number and case.","In this lesson, we will take a look at the basic nominative form of definite articles. Or simply, the equivalent of ''the'' in German."];var narration = ["Der = The (masculine)","Die = The (feminine)","Die = The (plural)","Das = The (neuter)","These words are the German definite articles in the nominative case.",""];var forTitles = ["Der","Die","Die","Das"];var engTitles = ["The (masculine)","The (feminine)","The (plural)","The (neuter)"];var forSideTitles = forTitles;var engSideTitles = engTitles;var titleSkip = [false,false,false,false,false];var exampleNums = [4,4,4,4];var forExamples = ["<strong>Der</strong> Vater","<strong>Der</strong> Wagen","<strong>Der</strong> Freund","<strong>Der</strong> Kuchen","<strong>Die</strong> Schwester","<strong>Die</strong> Katze","<strong>Die</strong> Sonne","<strong>Die</strong> Pflanze","<strong>Die</strong> Großväter","<strong>Die</strong> Tanten","<strong>Die</strong> Hemden","<strong>Die</strong> Züge","<strong>Das</strong> Haus","<strong>Das</strong> Buch","<strong>Das</strong> Pferd","<strong>Das</strong> Spielzeug"];var engExamples = ["<em>The</em> father (masculine)","<em>The</em> vehicle (masculine)","<em>The</em> friend (masculine)","<em>The</em> cake (masculine)","<em>The</em> sister (feminine)","<em>The</em> cat (feminine)","<em>The</em> sun (feminine)","<em>The</em> plant (feminine)","<em>The</em> grandfathers (plural)","<em>The</em> aunts (plural)","<em>The</em> shirts (plural)","<em>The</em> trains (plural)","<em>The</em> house (neuter)","<em>The</em> book (neuter)","<em>The</em> horse (neuter)","<em>The</em> toy (neuter)"];

var forExtra1 = ["<strong>Der</strong> Garten hat keine Zwiebel.","<strong>Der</strong> Junge ist im Begriff zu weinen.","<strong>Der</strong> Gartenschlauch ist biegsam.","<strong>Der</strong> arme Mann hat keine Schuhe.","<strong>Der</strong> Kaffee ist nicht mehr heiß.","<strong>Der</strong> Film beginnt um acht Uhr.","<strong>Der</strong> Löwe ist größer als ein Puma.","<strong>Der</strong> Schmerz ist schlimmer als gewöhnlich."];var engExtra1 = ["<em>The</em> garden has no onion. <i class='qhint'>(masculine)</i>","<em>The</em> boy is about to cry. <i class='qhint'>(masculine)</i>","<em>The</em> garden hose is flexible. <i class='qhint'>(masculine)</i>","<em>The</em> poor man has no shoes. <i class='qhint'>(masculine)</i>","<em>The</em> coffee is no longer hot. <i class='qhint'>(masculine)</i>","<em>The</em> movie starts at eight o'clock. <i class='qhint'>(masculine)</i>","<em>The</em> lion is bigger than a puma. <i class='qhint'>(masculine)</i>","<em>The</em> pain is worse than usual. <i class='qhint'>(masculine)</i>"];var imageExtra1 = ["../../block/64/images/pic6.jpg","../../verb/44/images/pic1.jpg","../../vocab/9/images/pic5.jpg","../../block/64/images/pic9.jpg","../../block/67/images/pic2.jpg","../../block/16/images/pic9.jpg","../../block/79/images/pic5.jpg","../../vocab/35/images/pic4.jpg"];var fastExtra1 = ["../../block/64/sounds/sound11","../../verb/44/sounds/sound3","../../vocab/9/sounds/sound15","../../block/64/sounds/sound17","../../block/67/sounds/sound3","../../block/16/sounds/sound17","../../block/79/sounds/sound9","../../vocab/35/sounds/sound15"];var slowExtra1 = ["../../block/64/sounds/sound12","../../verb/44/sounds/sound4","../../vocab/9/sounds/sound16","../../block/64/sounds/sound18","../../block/67/sounds/sound4","../../block/16/sounds/sound18","../../block/79/sounds/sound10","../../vocab/35/sounds/sound16"];

var forExtra2 = ["Ja. Sofort. Hier ist <strong>die</strong> Speisekarte...","Jetzt nimmst du <strong>die</strong> rechte Fahrbahn.","Er schwimmt gegen <strong>die</strong> Strömung.","Eine Wolke zieht vor <strong>die</strong> Sonne.","Bald! Wann ist <strong>die</strong> nächste Abfahrt?","Ihr repariertet <strong>die</strong> Klimaanlage.","<strong>Die</strong> Wüste ist ein sehr trockener Ort.","Ja, kommt sofort. Hier ist <strong>die</strong> Rechnung..."];var engExtra2 = ["Yes. Right away. Here is <em>the</em> menu... <i class='qhint'>(feminine)</i>","Now, you take <em>the</em> right lane. <i class='qhint'>(feminine)</i>","He is swimming against <em>the</em> current. <i class='qhint'>(feminine)</i>","A cloud passes in front of <em>the</em> sun. <i class='qhint'>(feminine)</i>","Soon! When is <em>the</em> next departure? <i class='qhint'>(feminine)</i>","You were repairing <em>the</em> air conditioner. <i class='qhint'>(feminine)</i>","<em>The</em> desert is a very dry place. <i class='qhint'>(feminine)</i>","Yes, right away. Here is <em>the</em> bill... <i class='qhint'>(feminine)</i>"];


var imageExtra2 = ["../../convo/images/convo8A.jpg","../../verb/103/images/pic2.jpg","../../block/21/images/pic3.jpg","../../block/28/images/pic4.jpg","../../convo/images/convo29B.jpg","../../verb/87/images/pic4.jpg","../../vocab/94/images/pic8.jpg","../../convo/images/convo10A.jpg"];var fastExtra2 = ["../../convo/8/sounds/1fast5","../../verb/103/sounds/sound7","../../block/21/sounds/sound5","../../block/28/sounds/sound7","../../convo/29/sounds/2fast4","../../verb/87/sounds/sound15","../../vocab/94/sounds/sound31","../../convo/10/sounds/1fast3"];var slowExtra2 = ["../../convo/8/sounds/1slow5","../../verb/103/sounds/sound8","../../block/21/sounds/sound6","../../block/28/sounds/sound8","../../convo/29/sounds/2slow4","../../verb/87/sounds/sound16","../../vocab/94/sounds/sound32","../../convo/10/sounds/1slow3"];

var forExtra3 = ["<strong>Die</strong> Kinder spielten den ganzen Tag.","<strong>Die</strong> Kinder werden frische Donuts essen.","<strong>Die</strong> besten Dinge im Leben sind gratis.","Könnten Sie bitte <strong>die</strong> Bettwäsche wechseln?","Ihr könnt jetzt <strong>die</strong> Kerzen ausblasen.","<strong>Die</strong> Freunde möchten zu Hause bleiben."];

var engExtra3 = ["<em>The</em> children played all day. <i class='qhint'>(plural)</i>","<em>The</em> children will eat fresh donuts. <i class='qhint'>(plural)</i>","<em>The</em> best things in life are free. <i class='qhint'>(plural)</i>","Could you please change <em>the</em> sheets? <i class='qhint'>(plural)</i>","You can now blow out <em>the</em> candles. <i class='qhint'>(plural)</i>","<em>The</em> friends would like to stay home. <i class='qhint'>(plural)</i>"];
var imageExtra3 = ["../../block/85/images/pic6.jpg","../../verb/51/images/pic5.jpg","../../vocab/92/images/pic7.jpg","../../convo/images/convo7B.jpg","../../verb/19/images/pic10.jpg","../../verb/99/images/pic1.jpg"];
var fastExtra3 = ["../../block/85/sounds/sound11","../../verb/51/sounds/sound19","../../vocab/92/sounds/sound27","../../convo/7/sounds/2fast6","../../verb/19/sounds/sound39","../../verb/99/sounds/sound3"];
var slowExtra3 = ["../../block/85/sounds/sound12","../../verb/51/sounds/sound20","../../vocab/92/sounds/sound28","../../convo/7/sounds/2slow6","../../verb/19/sounds/sound40","../../verb/99/sounds/sound4"];

var forExtra4 = ["Ihr lächelt für <strong>das</strong> Foto.","<strong>Das</strong> Kind scheint Hilfe zu brauchen.","<strong>Das</strong> Auto beschleunigt schnell.","<strong>Das</strong> Wasser des Schwimmbads ist türkis.","Vorsicht, <strong>das</strong> Gericht ist sehr heiß.","<strong>Das</strong> Auto funktionierte nicht normal."];

var engExtra4 = ["You are smiling for <em>the</em> picture. <i class='qhint'>(neuter)</i>","<em>The</em> child seems to need help. <i class='qhint'>(neuter)</i>","<em>The</em> car is accelerating quickly. <i class='qhint'>(neuter)</i>","<em>The</em> water of the swimming pool is turquoise. <i class='qhint'>(neuter)</i>","Be careful, <em>the</em> dish is very hot. <i class='qhint'>(neuter)</i>","<em>The</em> car was not functioning normally. <i class='qhint'>(neuter)</i>"];

var imageExtra4 = ["../../block/38/images/pic10.jpg","../../verb/79/images/pic1.jpg","../../verb/134/images/pic3.jpg","../../vocab/7/images/pic13.jpg","../../vocab/94/images/pic5.jpg","../../verb/137/images/pic3.jpg"];

var fastExtra4 = ["../../block/38/sounds/sound19","../../verb/79/sounds/sound3","../../verb/134/sounds/sound11","../../vocab/7/sounds/sound49","../../vocab/94/sounds/sound19","../../verb/137/sounds/sound11"];

var slowExtra4 = ["../../block/38/sounds/sound20","../../verb/79/sounds/sound4","../../verb/134/sounds/sound12","../../vocab/7/sounds/sound50","../../vocab/94/sounds/sound20","../../verb/137/sounds/sound12"];

