var lessonNumber = 10;var lessonTitle = "Fahren (To go)";var forExamples = ["Fahren","Diesen Sommer will ich nach Russland <strong>fahren</strong>.","ich fahre","<strong>Ich fahre</strong> zur Arbeit mit meinem alten Auto.","ich fahre","<strong>Ich fahre</strong> zur Arbeit am anderen Ende der Stadt.","du fährst","<strong>Fährst</strong> <em>du</em> heute nach Toronto?","du fährst","<strong>Du fährst</strong> zur Bäckerei, um Brot zu kaufen.","er fährt","<strong>Er fährt</strong> viel zu schnell!","sie fährt","<strong>Sie fährt</strong> zum Krankenhaus, weil sie sich ihren Arm gebrochen hat.","wir fahren","<strong>Wir fahren</strong> nach Frankreich, um den Eiffelturm zu sehen.","wir fahren","<strong>Wir fahren</strong> mit unseren Kindern zur Schule.","ihr fahrt","Da <strong>ihr</strong> zum Lebensmittelladen <strong>fahrt</strong>, könnt ihr mir eine Tüte Milch mitbringen?","ihr fahrt","Einmal im Jahr <strong>fahrt</strong> <em>ihr</em> zum Haus eurer Großeltern auf dem Land.","Sie fahren","Jeden Tag <strong>fahren</strong> <em>Sie</em> zum Einkaufszentrum.","sie fahren","<strong>Sie fahren</strong> mit dem Zug nach Deutschland.","sie fahren","<strong>Sie fahren</strong> nach Hause nach einem langen Arbeitstag."];var engExamples = ["To go","This summer, I want <em>to go</em> to Russia.","I go","<em>I go</em> to work with my old car.","I am going","<em>I am going</em> to work on the other side of town.","you are going","<em>Are you going</em> to Toronto today?","you go","<em>You go</em> to the bakery to buy bread.","he is going","<em>He is going</em> way too fast!","she is going","<em>She is going</em> to the hospital because she broke her arm.","we are going","<em>We are going</em> to France to see the Eiffel Tower.","we are going","<em>We are going</em> to school with our children.","you are going","Since <em>you are going</em> to the grocery store, could you get me a carton of milk?","you go","Once a year, <em>you go</em> to your grandparents' house in the countryside.","you go","<em>You go</em> to the shopping mall every day.","they go","<em>They go</em> to Germany by train.","they go","<em>They go</em> home after a long day of work."];var btnColor = ["#1EEC00","#163F00"];

var forConj1 = ["ich fahr<strong>e</strong>","du f<em>ä</em>hr<strong>st</strong>","er/sie/es f<em>ä</em>hr<strong>t</strong>","wir fahr<strong>en</strong>","ihr fahr<strong>t</strong>","Sie fahr<strong>en</strong>","sie fahr<strong>en</strong>"];
var quizConj1 = ["fahre","fährst","fährt","fahren","fahrt","fahren"];

var forConj2 = ["ich bin <strong>ge</strong>fahr<strong>en</strong>","du bist <strong>ge</strong>fahr<strong>en</strong>","er/sie/es ist <strong>ge</strong>fahr<strong>en</strong>","wir sind <strong>ge</strong>fahr<strong>en</strong>","ihr seid <strong>ge</strong>fahr<strong>en</strong>","Sie sind <strong>ge</strong>fahr<strong>en</strong>","sie sind <strong>ge</strong>fahr<strong>en</strong>"];
var quizConj2 = ["bin gefahren","bist gefahren","ist gefahren","sind gefahren","seid gefahren","sind gefahren"];

var forConj3 = ["ich f<em>u</em>hr","du f<em>u</em>hr<strong>st</strong>","er/sie/es f<em>u</em>hr","wir f<em>u</em>hr<strong>en</strong>","ihr f<em>u</em>hr<strong>t</strong>","Sie f<em>u</em>hr<strong>en</strong>","sie f<em>u</em>hr<strong>en</strong>"];
var quizConj3 = ["fuhr","fuhrst","fuhr","fuhren","fuhrt","fuhren"];

var forConj4 = ["ich werde fahr<strong>en</strong>","du wirst fahr<strong>en</strong>","er/sie/es wird fahr<strong>en</strong>","wir werden fahr<strong>en</strong>","ihr werdet fahr<strong>en</strong>","Sie werden fahr<strong>en</strong>","sie werden fahr<strong>en</strong>"];
var quizConj4 = ["werde fahren","wirst fahren","wird fahren","werden fahren","werdet fahren","werden fahren"];

var forConj5 = ["ich würde fahr<strong>en</strong>","du würdest fahr<strong>en</strong>","er/sie/es würde fahr<strong>en</strong>","wir würden fahr<strong>en</strong>","ihr würdet fahr<strong>en</strong>","Sie würden fahr<strong>en</strong>","sie würden fahr<strong>en</strong>"];
var quizConj5 = ["würde fahren","würdest fahren","würde fahren","würden fahren","würdet fahren","würden fahren"];

var engConj1  = ["I go / am going","you go / are going (informal)","he/she/it goes / is going","we go / are going","you go / are going (plural)","you go / are going (formal)","they go / are going"];
var engConj2  = ["I went","you went (informal)","he/she/it went","we went","you went (plural)","you went (formal)","they went"];
var engConj3  = ["I was going","you were going (informal)","he/she/it was going","we were going","you were going (plural)","you were going (formal)","they were going"];
var engConj4  = ["I will go","you will go (informal)","he/she/it will go","we will go","you will go (plural)","you will go (formal)","they will go"];
var engConj5  = ["I would go","you would go (informal)","he/she/it would go","we would go","you would go (plural)","you would go (formal)","they would go"];

var verbTypeNum = "7";var forConj6 = "Sein";var forConj7 = "F_hr";var pronominal = false;var conjNum = [0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1];

var irregReason = ['This verb is strong because the "a" in the stem changes to a "u" in some of the conjugation. The change is shown in black in this lesson.'];
var quizForExamples = ["<strong>Ich fahre</strong> durch die Stadt.","<strong>Du fährst</strong> zur Kirche jeden Sonntag.","<strong>Er fährt</strong> nach New York, um ein paar Freunde zu treffen.","Da das Wetter schön ist, <strong>fahren</strong> <em>wir</em> zum Schwimmbad.","Ich weiß, dass <strong>ihr</strong> oft zum Park <strong>fahrt</strong>, um ohne mich Fußball zu spielen.","<strong>Sie fahren</strong> schnell, weil sie zu spät zum Treffen kommen."];var quizEngExamples = ["<em>I go</em> through the town.","<em>You go</em> to church every Sunday.","<em>He goes</em> to New York to meet some friends.","Since the weather is nice, <em>we are going</em> to the swimming pool.","I know that <em>you</em> often <em>go</em> to the park to play soccer without me.","<em>They are going</em> fast because they are late for the meeting."];

var extraNote = 'The verb <strong>to go</strong> in German is a little particular. There are a few main verbs meaning <strong>to go</strong> and each verb is specific to the method used to get there. When you <strong>go</strong> by car, by bicycle or by public transport (basically whenever you <em>go on wheels</em>), the verb <strong>fahren</strong> is used.';