var quizLessonBoth = "noQuiz";var lessonNumber = 104;var numOfAllQuiz = 105;var lessonTitle = "Weitere wichtige Wörter II (More Important Words - Part 1)";var btnColor = ["#00BFFF","#001E51","#0066FF","#00025B"];var quesToRemove = [];var startNarration = [];var narration = ["","","","","","",""];var forTitles = ["Jemals","Allerdings","Natürlich","Anderes","Bereit"];var engTitles = ["Ever (at least once)","However","Of course","Else","Ready"];var forSideTitles = forTitles;var engSideTitles = engTitles;var titleSkip = [false,false,false,false,false];var exampleNums = [3,3,3,3,3];var forExamples = ["Bist du <strong>jemals</strong> nach Europa gereist?","Hast du <strong>jemals</strong> den Ozean gesehen?","Warst du <strong>jemals</strong> mein Freund?","Wir haben heute Nacht ein Zimmer frei, <strong>allerdings</strong> ist es noch nicht fertig.","Es regnete draußen; <strong>allerdings</strong> hatten sie trotzdem eine gute Zeit.","Ich lief heute zehn Kilometer; <strong>allerdings</strong> möchte ich noch mehr laufen.","<strong>Natürlich</strong> würde ich gerne mit dir arbeiten.","<strong>Natürlich</strong> erinnere ich mich an dich!","Möchtest du mit uns kommen? <strong>Natürlich</strong>!","Möchtest du etwas <strong>anderes</strong>?","Ich habe nichts <strong>anderes</strong>, das ich dir geben könnte.","Nichts <strong>anderes</strong> ist von Bedeutung.","Bist du <strong>bereit</strong>?","Wann werden sie <strong>bereit</strong> sein, zu gehen?","Ich bin <strong>bereit</strong> für die Prüfung morgen."];var engExamples = ["Have you <em>ever</em> (at least once) traveled to Europe?","Have you <em>ever</em> (at least once) seen the ocean?","Were you <em>ever</em> my friend?","We have a room for tonight; <em>however</em>, it is not ready yet.","It was raining outside; <em>however</em>, they still had a good time.","I ran ten kilometres today; <em>however</em>, I want to run even more.","<em>Of course,</em> I would be happy to work with you.","<em>Of course</em> I remember you!","Would you like to come with us? <em>Of course</em>!","Would you like anything <em>else</em>?","I have nothing <em>else</em> to give you.","Nothing <em>else</em> is important.","Are you <em>ready</em>?","When will they be <em>ready</em> to go?","I am <em>ready</em> for tomorrow's exam."];


var forExtra3 = ["Ja, <strong>natürlich</strong>, hier ist sie...","<strong>Natürlich</strong>, ich bin nicht blöd...","Ja, <strong>natürlich</strong>. Hier ist Ihr Stadtplan...","Falls Ihr Arm gebrochen ist, ja, <strong>natürlich</strong>.","<strong>Natürlich</strong> nicht... Meine Batterie ist fast leer."];
var engExtra3 = ["Yes, <em>of course</em>, here it is...","<em>Of course</em>, I'm not stupid...","Yes, <em>of course</em>. Here is your city map...","If your arm is broken, yes, <em>of course</em>.","<em>Of course</em> not... My battery is about to run out."];
var imageExtra3 = ["../../convo/images/convo31B.jpg","../../convo/images/convo26A.jpg","../../convo/images/convo17A.jpg","../../convo/images/convo22A.jpg","../../convo/images/convo4A.jpg"];
var fastExtra3 = ["../../convo/31/sounds/2fast1","../../convo/26/sounds/1fast6","../../convo/17/sounds/1fast7","../../convo/22/sounds/1fast6","../../convo/4/sounds/1fast9"];
var slowExtra3 = ["../../convo/31/sounds/2slow1","../../convo/26/sounds/1slow6","../../convo/17/sounds/1slow7","../../convo/22/sounds/1slow6","../../convo/4/sounds/1slow9"];



var forExtra4 = ["Sehr gut. Möchten Sie noch etwas <strong>anderes</strong> bestellen?","Nach Erreichen dieses Ziels werden wir etwas <strong>anderes</strong> begehren."];var engExtra4 = ["Very good. Do you want to order anything <em>else</em>?","After reaching this goal, we will desire something <em>else</em>."];var imageExtra4 = ["../../convo/images/convo50A.jpg","../../verb/149/images/pic4.jpg"];var fastExtra4 = ["../../convo/50/sounds/1fast5","../../verb/149/sounds/sound15"];var slowExtra4 = ["../../convo/50/sounds/1slow5","../../verb/149/sounds/sound16"];var forExtra5 = ["Du musst <strong>bereit</strong> sein, deine Reise zu lieben.","Er ist nicht ganz <strong>bereit</strong>, allein zu fahren."];var engExtra5 = ["You have to be <em>ready</em> to love your trip.","He is not quite <em>ready</em> to drive on his own."];var imageExtra5 = ["../../verb/76/images/pic1.jpg","../../block/66/images/pic2.jpg"];var fastExtra5 = ["../../verb/76/sounds/sound3","../../block/66/sounds/sound3"];var slowExtra5 = ["../../verb/76/sounds/sound4","../../block/66/sounds/sound4"];