var quizLessonBoth = "quiz";
var lessonNumber = 80;
var lessonTitle = "Die Steigerung (Comparison)";
var btnColor = ["#CC00E2","#4A0041","#AD00FF","#320058"];
////INCLUDE NUMBER IN LIST BELOW TO REMOVE QUESTION
var quesToRemove = [];
////LESSON CONTENT BELOW

var forExamples1 = ["Eine Maus ist klein<strong>er als</strong> ein Elefant.","Deine Zeichnung ist schön<strong>er als</strong> meine Zeichnung.","Du bist langsam<strong>er als</strong> eine Schildkröte!","Meine Großmutter ist alt, aber mein Großvater ist <em>ä</em>lt<strong>er</strong>.","Heute ist es k<em>ä</em>lt<strong>er als</strong> gestern.","Sabrina ist j<em>ü</em>ng<strong>er als</strong> Tom.","Ich bin viel intelligent<strong>er als</strong> mein Lehrer.","Diese Geschichte war unglaublich<strong>er als</strong> die letzte!","Mein Zimmer ist friedlich<strong>er als</strong> das Zimmer von meinem Mitbewohner."];var engExamples1 = ["A mouse is small<em>er than</em> an elephant.","Your drawing is bett<em>er than</em> my drawing.","You are slow<em>er than</em> a turtle!","My grandmother is old, but my grandfather is old<em>er</em>.","Today is cold<em>er than</em> yesterday.","Sabrina is young<em>er than</em> Tom.","I am much <em>more</em> intelligent <em>than</em> my teacher.","This story was <em>more</em> unbelievable <em>than</em> the last!","My room is <em>more</em> peaceful <em>than</em> the room of my roommate."];

var forExamples2 = ["Sie ist <em>so</em> stark <strong>wie</strong> ich","Der blaue Ball ist <strong>so</strong> schwer <em>wie</em> der grüne Ball.","Er arbeitet <em>so</em> viel <strong>wie</strong> sein Kollege.","Dein Auto ist <strong>nicht so</strong> schnell <em>wie</em> meins.","Er ist <em>nicht so</em> ängstlich <strong>wie</strong> ich.","Das braune Pferd ist <strong>nicht so</strong> alt <em>wie</em> das weiße.","München ist <em>nicht so</em> bewohnt <strong>wie</strong> Berlin.","Das Buch ist <strong>besser als</strong> der Film.","Diese Suppe ist <strong>besser als</strong> die letzte.","Er schreibt <strong>besser als</strong> ich.","Es ist <strong>besser als</strong> nichts.","Das Bett ist <strong>schlechter als</strong> das Sofa.","Die rote Mannschaft ist <strong>schlechter als</strong> die blaue Mannschaft.","Das neue Auto ist <strong>schlechter als</strong> das alte.","Die Lage ist <strong>schlechter als</strong> sie dachte."];var engExamples2 = ["She is <em>as</em> strong <em>as</em> I am.","The blue ball is <em>as</em> heavy <em>as</em> the green ball.","He works <em>as</em> much <em>as</em> his colleague.","Your car is <em>not as</em> fast <em>as</em> mine.","He is <em>not as</em> scared <em>as</em> I (am).","The brown horse is <em>not as</em> old <em>as</em> the white one.","Munich is <em>not as</em> populated <em>as</em> Berlin.","The book is <em>better than</em> the movie.","This soup is <em>better than</em> the last one.","He writes <em>better than</em> I.","It's <em>better than</em> nothing.","The bed is <em>worse than</em> the couch.","The red team is <em>worse than</em> the blue team.","The new car is <em>worse than</em> the old one.","The situation is <em>worse than</em> she thought."];

var forExamples3 = ["Ich denke, dass dieser Film <em>am</em> lustig<strong>sten</strong> ist.","Das Lied, das du geschrieben hast, ist <strong>am</strong> traurig<em>sten</em>.","Herr Schmidt ist <em>am</em> reich<strong>sten</strong>.","Rosa ist <strong>am</strong> schön<em>sten</em>.","Dieses Seil ist <em>am</em> l<em>ä</em>ng<strong>sten</strong>.","Du bist <strong>am</strong> verrückt<em>esten</em>!","Seine Freundin ist <em>am</em> hübsch<strong>esten</strong>.","Alexander ist <em>am</em> intelligent<strong>esten</strong>.","Sie ist <em>das</em> am <strong>wenigsten</strong> begabte Mitglied der Gruppe.","Petra ist <em>die</em> am <strong>wenigsten</strong> interessante Person in dem Büro.","Günter ist <em>der</em> am <strong>wenigsten</strong> Beteiligte bei der Arbeit.","Dieses Auto ist <strong>der beste</strong> Wagen, den ich je gehabt habe.","Sie ist <strong>die beste</strong> Athletin in ihrer Mannschaft.","Sie ist <strong>die beste</strong> Sängerin in der Band.","Ingrid ist <strong>die schlechteste</strong> Studentin an der Universität.","Frau Müller ist <strong>die schlechteste</strong> Lehrerin an der Schule.","Du bist wirklich <strong>der schlechteste</strong> Musiker!"];var engExamples3 = ["I think that this movie is the funni<em>est</em>.","The song that you have written is the sadd<em>est</em>.","Mister Schmidt is the wealthi<em>est</em>.","Rosa is the pretti<em>est</em>.","This rope is the long<em>est</em>.","You are the crazi<em>est</em>!","His girlfriend is <em>the most</em> beautiful.","Alexander is <em>the most</em> intelligent.","She is <em>the least</em> talented member of the group.","Petra is <em>the least</em> interesting person in the office.","Günter is <em>the least</em> involved at work.","This car is <em>the best</em> vehicle I have ever had.","She is <em>the best</em> athlete on her team.","She is <em>the best</em> singer in the band.","Ingrid is <em>the worst</em> student of the university.","Miss Müller is <em>the worst</em> teacher in the school.","You really are <em>the worst</em> musician!"];

var forExamples4 = ["Ich trinke <strong>gern</strong> Wasser.","Aber ich möchte <strong>lieber</strong> Limonade trinken.","<strong>Am liebsten</strong>, würde ich ein Glas Wein trinken.","Ein Puma ist wie eine <strong>große</strong> Katze.","Der Löwe ist <strong>größer</strong> als ein Puma.","Der Tiger ist <strong>am größten</strong>.","Heute fühle ich mich <strong>gut</strong>.","Ich fühle mich <strong>besser</strong> als gestern.","Dieses Gefühl ist <strong>am besten</strong>!","Der Vogel ist <strong>hoch</strong> am Himmel.","Der Heißluftballon ist <strong>höher</strong> als der Vogel.","Das Flugzeug ist <strong>am höchsten</strong> am Himmel.","Ich wohne <strong>nahe</strong> bei Frankfurt.","München ist <strong>näher</strong> an Italien als an Hamburg.","Ich weiß nicht, welche Stadt <strong>am nächsten</strong> ist."];var engExamples4 = ["I <em>gladly</em> drink water.","But I would <em>rather</em> drink lemonade.","<em>Most preferably</em>, I would have a glass of wine.","A puma is like a <em>big</em> cat.","The lion is <em>bigger</em> than a puma.","The tiger is <em>the biggest</em>.","I feel <em>good</em> today.","I feel <em>better</em> than yesterday.","This feeling is <em>the best</em>!","The bird is <em>high</em> in the sky.","The hot air balloon is <em>higher</em> than the bird.","The plane is <em>the highest</em> in the sky.","I live <em>near</em> Frankfurt.","Munich is <em>nearer</em> (closer) to Italy than Hamburg.","I don't know which city is <em>the nearest</em>."];