var lessonNumber = 60;var lessonTitle = "Spazieren gehen (To go for a walk)";var forExamples = ["Spazieren gehen","Sie liebt es, im Herbst im Park <strong>spazieren</strong> zu <strong>gehen</strong>.","sie gehen spazieren","Wenn es schneit, <strong>gehen sie spazieren</strong>.","wir sind spazieren gegangen","<strong>Wir sind</strong> vier Stunden <strong>spazieren gegangen</strong>.","du gingst spazieren","<strong>Du gingst</strong> jeden Tag mit deinem Hund <strong>spazieren</strong>.","ich werde spazieren gehen","<strong>Ich werde</strong> heute fünf Kilometer im Schnee <strong>spazieren gehen</strong>.","sie würde spazieren gehen","Wenn sie hier leben würde, <strong>würde sie</strong> immer am Strand <strong>spazieren gehen</strong>."];var engExamples = ["To go for a walk","She likes <em>to go for a walk</em> in the park in the fall.","they go for a walk","When it's snowing, <em>they go for a walk</em>.","we went for a walk","<em>We went for a walk</em> for four hours.","you were going for a walk","<em>You were going for a walk</em> with your dog every day.","I will go for a walk","<em>I will walk</em> five kilometres in the snow today.","she would go for a walk","If she lived here, <em>she would</em> always <em>go for a walk</em> on the beach."];var btnColor = ["#FFC400","#BB0A00"];

var forConj1 = ["ich geh<strong>e</strong> spazieren","du geh<strong>st</strong> spazieren","er/sie/es geh<strong>t</strong> spazieren","wir geh<strong>e</strong><strong>n</strong> spazieren","ihr geh<strong>t</strong> spazieren","Sie geh<strong>e</strong><strong>n</strong> spazieren","sie geh<strong>e</strong><strong>n</strong> spazieren"];
var quizConj1 = ["gehe spazieren","gehst spazieren","geht spazieren","gehen spazieren","geht spazieren","gehen spazieren"];

var forConj2 = ["ich bin spazieren <strong>ge</strong>g<em>ang</em><strong>en</strong>","du bist spazieren <strong>ge</strong>g<em>ang</em><strong>en</strong>","er/sie/es ist spazieren <strong>ge</strong>g<em>ang</em><strong>en</strong>","wir sind spazieren <strong>ge</strong>g<em>ang</em><strong>en</strong>","ihr seid spazieren <strong>ge</strong>g<em>ang</em><strong>en</strong>","Sie sind spazieren <strong>ge</strong>g<em>ang</em><strong>en</strong>","sie sind spazieren <strong>ge</strong>g<em>ang</em><strong>en</strong>"];
var quizConj2 = ["bin spazieren gegangen","bist spazieren gegangen","ist spazieren gegangen","sind spazieren gegangen","seid spazieren gegangen","sind spazieren gegangen"];

var forConj3 = ["ich g<em>ing</em> spazieren","du g<em>ing</em><strong>st</strong> spazieren","er/sie/es g<em>ing</em> spazieren","wir g<em>ing</em><strong>en</strong> spazieren","ihr g<em>ing</em><strong>t</strong> spazieren","Sie g<em>ing</em><strong>en</strong> spazieren","sie g<em>ing</em><strong>en</strong> spazieren"];
var quizConj3 = ["ging spazieren","gingst spazieren","ging spazieren","gingen spazieren","gingt spazieren","gingen spazieren"];

var forConj4 = ["ich werde spazieren geh<strong>e</strong><strong>n</strong>","du wirst spazieren geh<strong>e</strong><strong>n</strong>","er/sie/es wird spazieren geh<strong>e</strong><strong>n</strong>","wir werden spazieren geh<strong>e</strong><strong>n</strong>","ihr werdet spazieren geh<strong>e</strong><strong>n</strong>","Sie werden spazieren geh<strong>e</strong><strong>n</strong>","sie werden spazieren geh<strong>e</strong><strong>n</strong>"];
var quizConj4 = ["werde spazieren gehen","wirst spazieren gehen","wird spazieren gehen","werden spazieren gehen","werdet spazieren gehen","werden spazieren gehen"];

var forConj5 = ["ich würde spazieren geh<strong>e</strong><strong>n</strong>","du würdest spazieren geh<strong>e</strong><strong>n</strong>","er/sie/es würde spazieren geh<strong>e</strong><strong>n</strong>","wir würden spazieren geh<strong>e</strong><strong>n</strong>","ihr würdet spazieren geh<strong>e</strong><strong>n</strong>","Sie würden spazieren geh<strong>e</strong><strong>n</strong>","sie würden spazieren geh<strong>e</strong><strong>n</strong>"];
var quizConj5 = ["würde spazieren gehen","würdest spazieren gehen","würde spazieren gehen","würden spazieren gehen","würdet spazieren gehen","würden spazieren gehen"];

var engConj1  = ["I go for a walk","you go for a walk (informal)","he/she/it goes for a walk","we go for a walk","you go for a walk (plural)","you go for a walk (formal)","they go for a walk"];
var engConj2  = ["I went for a walk","you went for a walk (informal)","he/she/it went for a walk","we went for a walk","you went for a walk (plural)","you went for a walk (formal)","they went for a walk"];
var engConj3  = ["I was going for a walk","you were going for a walk (informal)","he/she/it was going for a walk","we were going for a walk","you were going for a walk (plural)","you were going for a walk (formal)","they were going for a walk"];
var engConj4  = ["I will go for a walk","you will go for a walk (informal)","he/she/it will go for a walk","we will go for a walk","you will go for a walk (plural)","you will go for a walk (formal)","they will go for a walk"];
var engConj5  = ["I would go for a walk","you would go for a walk (informal)","he/she/it would go for a walk","we would go for a walk","you would go for a walk (plural)","you would go for a walk (formal)","they would go for a walk"];

var verbTypeNum = "7";var forConj6 = "Sein";var forConj7 = "G";var pronominal = false;var conjNum = [0,0,1,1,2,2,3,3,4,4,5,5];

var irregReason = ['This verb is strong because the "e" in the stem changes to an "i" or an "a" in some of the conjugation. The "h" in the stem also changes to "ng" in some of the conjugation. The changes are shown in black in this lesson.'];
var extraNote = 'This verb is different from most verbs. The closest equivalent in English would be "to go for a walk".<br>Also, verbs ending in <strong>-ieren</strong> do not have the prefix <strong>ge-</strong> in front of the past participle.';