var quizLessonBoth = "lesson";var lessonNumber = 58;var numOfAllQuiz = 61;var lessonTitle = "Demonstrativadjektiv - Part I (Demonstrative adjectives)";var btnColor = ["#1EEC00","#163F00","#90E700","#254800"];var quesToRemove = [];var startNarration = ["German demonstrative adjectives are fairly simple and are used in a way that's very similar to English.","The German word ''dieser'' means ''this'' and is used when the object is close.","However, it is also used in a lot of situations where you would use ''that'' in English.","Note that it changes a little depending on the gender and number, and it also declines. In this lesson, we will take a look at the nominative form."];var narration = ["","","",""];var forTitles = ["Dieser","Dieses","Diese","Diese"];var engTitles = ["This (masculine)","This (neuter)","This (feminine)","These"];var forSideTitles = forTitles;var engSideTitles = engTitles;var titleSkip = [false,false,false,false,false];var exampleNums = [3,3,3,3];var forExamples = ["<strong>Dieser</strong> Wagen kann sehr schnell fahren.","<strong>Dieser</strong> Stuhl scheint fragil.","<strong>Dieser</strong> Affe spielt mit dem Seil.","<strong>Dieses</strong> Gebäude ist hoch.","<strong>Dieses</strong> Hemd ist weiß","Wir werden <strong>dieses</strong> Kanu nehmen.","Ich liebe <strong>diese</strong> Gitarre.","<strong>Diese</strong> Blume ist schön","Ich habe <strong>diese</strong> Brieftasche gefunden.","Ich will <strong>diese</strong> Schuhe.","<strong>Diese</strong> Beeren sind köstlich","Ich werde <strong>diese</strong> Filme ausleihen."];var engExamples = ["<em>This</em> vehicle can go very fast. (masculine)","<em>This</em> chair seems fragile. (masculine)","<em>This</em> ape plays with the rope. (masculine)","<em>This</em> building is tall. (neuter)","<em>This</em> shirt is white. (neuter)","We are going to take <em>this</em> canoe. (neuter)","I love <em>this</em> guitar. (feminine)","<em>This</em> flower is beautiful. (feminine)","I have found <em>this</em> wallet. (feminine)","I want <em>these</em> shoes.","<em>These</em> berries are delicious.","I will rent <em>these</em> movies."];

var forExtra1 = ["<strong>Dieser</strong> Mantel gehört mir.","<strong>Dieser</strong> Karton ist deiner.","<strong>Dieser</strong> Hund ist sehr groß.","<strong>Dieser</strong> Kuchen ist für euch.","<strong>Dieser</strong> Baum ist wirklich groß.","<strong>Dieser</strong> Staubsauger ist unserer.","<strong>Dieser</strong> frische Zitronensaft ist sauer.","Es sind keine Männer in <strong>dieser</strong> Gruppe.","Mensch! <strong>Dieser</strong> Typ liebt sich wirklich!","Ich glaube, dass <strong>dieser</strong> Stift seiner ist.","Ich denke, dass <strong>dieser</strong> Film am lustigsten ist."];


var engExtra1 = ["<em>This</em> coat belongs to me. (masculine)","<em>This</em> package is yours. (masculine)","<em>This</em> dog is very big. (masculine)","<em>This</em> cake is for you. (masculine)","<em>This</em> tree is really tall. (masculine)","<em>This</em> vacuum cleaner is ours. (masculine)","<em>This</em> fresh lemon juice is sour. (masculine)","There are no men in <em>this</em> group. (masculine)","Gee! <em>This</em> guy really loves himself! (masculine)","I believe that <em>this</em> pen is his. (masculine)","I think that <em>this</em> movie is the funniest. (masculine)"];


var imageExtra1 = ["../../block/45/images/pic3.jpg","../../block/55/images/pic6.jpg","../../vocab/38/images/pic11.jpg","../../block/42/images/pic12.jpg","../../vocab/35/images/pic9.jpg","../../block/56/images/pic2.jpg","../../block/98/images/pic1.jpg","../../vocab/89/images/pic3.jpg","../../block/50/images/pic2.jpg","../../block/55/images/pic9.jpg","../../block/78/images/pic1.jpg"];var fastExtra1 = ["../../block/45/sounds/sound5","../../block/55/sounds/sound11","../../vocab/38/sounds/sound43","../../block/42/sounds/sound23","../../vocab/35/sounds/sound35","../../block/56/sounds/sound3","../../block/98/sounds/sound1","../../vocab/89/sounds/sound9","../../block/50/sounds/sound3","../../block/55/sounds/sound17","../../block/78/sounds/sound1"];var slowExtra1 = ["../../block/45/sounds/sound6","../../block/55/sounds/sound12","../../vocab/38/sounds/sound44","../../block/42/sounds/sound24","../../vocab/35/sounds/sound36","../../block/56/sounds/sound4","../../block/98/sounds/sound2","../../vocab/89/sounds/sound10","../../block/50/sounds/sound4","../../block/55/sounds/sound18","../../block/78/sounds/sound2"];var forExtra2 = ["Ist <strong>dieses</strong> Haus ihres?","Okay. Ich nehme <strong>dieses</strong> Gericht.","<strong>Dieses</strong> Haus hat kein Dach!","<strong>Dieses</strong> Seil ist am längsten.","<strong>Dieses</strong> Gefühl ist am besten!","Ich mag <strong>dieses</strong> Foto von dir.","<strong>Dieses</strong> Restaurant ist Ihres.","Du singst <strong>dieses</strong> Lied sehr gut.","Du wirst <strong>dieses</strong> Auto reparieren.","<strong>Dieses</strong> Auto ist nur ein Modell.","Ich habe <strong>dieses</strong> lila Hemd gewählt.","<strong>Dieses</strong> Geschenk ist für meinen Sohn."];

var engExtra2 = ["Is <em>this</em> house theirs? (neuter)","Okay. I will take <em>this</em> dish. (neuter)","<em>This</em> house has no roof! (neuter)","<em>This</em> rope is the longest. (neuter)","<em>This</em> feeling is the best! (neuter)","I like <em>this</em> picture of you. (neuter)","<em>This</em> restaurant is yours. (neuter)","You sing <em>this</em> song very well. (neuter)","You will repair <em>this</em> car. (neuter)","<em>This</em> car is only a model. (neuter)","I chose <em>this</em> purple shirt. (neuter)","<em>This</em> present is for my son. (neuter)"];


var imageExtra2 = ["../../block/56/images/pic10.jpg","../../convo/images/convo9B.jpg","../../block/64/images/pic4.jpg","../../block/78/images/pic5.jpg","../../block/79/images/pic9.jpg","../../block/46/images/pic4.jpg","../../block/55/images/pic12.jpg","../../verb/93/images/pic2.jpg","../../verb/148/images/pic2.jpg","../../vocab/88/images/pic6.jpg","../../verb/39/images/pic3.jpg","../../block/20/images/pic3.jpg"];var fastExtra2 = ["../../block/56/sounds/sound19","../../convo/9/sounds/2fast3","../../block/64/sounds/sound7","../../block/78/sounds/sound9","../../block/79/sounds/sound17","../../block/46/sounds/sound7","../../block/55/sounds/sound23","../../verb/93/sounds/sound7","../../verb/148/sounds/sound7","../../vocab/88/sounds/sound19","../../verb/39/sounds/sound11","../../block/20/sounds/sound5"];var slowExtra2 = ["../../block/56/sounds/sound20","../../convo/9/sounds/2slow3","../../block/64/sounds/sound8","../../block/78/sounds/sound10","../../block/79/sounds/sound18","../../block/46/sounds/sound8","../../block/55/sounds/sound24","../../verb/93/sounds/sound8","../../verb/148/sounds/sound8","../../vocab/88/sounds/sound20","../../verb/39/sounds/sound12","../../block/20/sounds/sound6"];var forExtra3 = ["<strong>Diese</strong> Kamera ist ihre.","<strong>Diese</strong> Information ist für dich.","Ja. Ich verstehe <strong>diese</strong> Frage nicht.","Wir haben <strong>diese</strong> teure Lampe gekauft.","Ja, ich werde dich <strong>diese</strong> Woche anrufen.","<strong>Diese</strong> Suppe ist besser als die letzte.","Sie haben <strong>diese</strong> Geschichte zigmal gelesen.","Sie ist nicht an <strong>diese</strong> Art Hitze gewöhnt.","Okay. Ist nicht wichtig, ich mag <strong>diese</strong> Farbe.","Wir haben <strong>diese</strong> Wohnung für ein Jahr gemietet.","Die Kinder werden sich an <strong>diese</strong> Reise erinnern."];


var engExtra3 = ["<em>This</em> camera is hers. (feminine)","<em>This</em> information is for you. (feminine)","Yes. I don't understand <em>this</em> question. (feminine)","We purchased <em>this</em> expensive lamp. (feminine)","Yeah, I am going to call you <em>this</em> week. (feminine)","<em>This</em> soup is better than the last one. (feminine)","They read <em>this</em> story dozens of times. (feminine)","She is not used to <em>this</em> kind of heat. (feminine)","Okay. It doesn't matter, I like <em>this</em> color. (feminine)","We rented <em>this</em> apartment for a year. (feminine)","The children will remember <em>this</em> trip. (feminine)"];var imageExtra3 = ["../../block/55/images/pic13.jpg","../../block/42/images/pic3.jpg","../../convo/images/convo15A.jpg","../../block/98/images/pic4.jpg","../../convo/images/convo40A.jpg","../../block/77/images/pic9.jpg","../../verb/83/images/pic3.jpg","../../vocab/87/images/pic6.jpg","../../convo/images/convo34B.jpg","../../verb/86/images/pic3.jpg","../../verb/85/images/pic5.jpg"];

var fastExtra3 = ["../../block/55/sounds/sound25","../../block/42/sounds/sound5","../../convo/15/sounds/1fast2","../../block/98/sounds/sound7","../../convo/40/sounds/1fast12","../../block/77/sounds/sound17","../../verb/83/sounds/sound11","../../vocab/87/sounds/sound15","../../convo/34/sounds/2fast6","../../verb/86/sounds/sound11","../../verb/85/sounds/sound19"];var slowExtra3 = ["../../block/55/sounds/sound26","../../block/42/sounds/sound6","../../convo/15/sounds/1slow2","../../block/98/sounds/sound8","../../convo/40/sounds/1slow12","../../block/77/sounds/sound18","../../verb/83/sounds/sound12","../../vocab/87/sounds/sound16","../../convo/34/sounds/2slow6","../../verb/86/sounds/sound12","../../verb/85/sounds/sound20"];


var forExtra4 = ["<strong>Diese</strong> Äpfel sind unsere.","<strong>Diese</strong> Spielsachen sind ihre.","Sind <strong>diese</strong> Kleider Ihre?","Sind alle <strong>diese</strong> Schuhe deine?","Alle <strong>diese</strong> Lutscher sind seine.","All <strong>diese</strong> Geschenke sind für dich.","Wir möchten <strong>diese</strong> Äpfel verkaufen.","All <strong>diese</strong> Äpfel sind sehr ähnlich.","Wir durften <strong>diese</strong> Bücher ausleihen."];

var engExtra4 = ["<em>These</em> apples are ours.","<em>These</em> toys are hers.","Are <em>these</em> clothes yours?","Are all <em>these</em> shoes yours?","All <em>these</em> lollipops are his.","All <em>these</em> gifts are for you.","We would like to sell <em>these</em> apples.","All <em>these</em> apples are very similar.","We were allowed to borrow <em>these</em> books."];



var imageExtra4 = ["../../block/56/images/pic3.jpg","../../block/55/images/pic14.jpg","../../block/55/images/pic11.jpg","../../block/55/images/pic5.jpg","../../block/55/images/pic7.jpg","../../block/42/images/pic2.jpg","../../verb/26/images/pic4.jpg","../../vocab/94/images/pic2.jpg","../../verb/29/images/pic4.jpg"];var fastExtra4 = ["../../block/56/sounds/sound5","../../block/55/sounds/sound27","../../block/55/sounds/sound21","../../block/55/sounds/sound9","../../block/55/sounds/sound13","../../block/42/sounds/sound3","../../verb/26/sounds/sound15","../../vocab/94/sounds/sound7","../../verb/29/sounds/sound15"];var slowExtra4 = ["../../block/56/sounds/sound6","../../block/55/sounds/sound28","../../block/55/sounds/sound22","../../block/55/sounds/sound10","../../block/55/sounds/sound14","../../block/42/sounds/sound4","../../verb/26/sounds/sound16","../../vocab/94/sounds/sound8","../../verb/29/sounds/sound16"];