var quizLessonBoth = "quiz";
var lessonNumber = 57;
var lessonTitle = "Das Possessivpronomen (Independent possessive pronouns)";
var btnColor = ["#FFC400","#BB0A00","#FFEE00","#B83D00"];
////INCLUDE NUMBER IN LIST BELOW TO REMOVE QUESTION
var quesToRemove = [];
////LESSON CONTENT BELOW
var forExamples1 = ["Das ist <em>mein Pizzastück</em>. Das ist <strong>meins</strong>.","Dein Hut ist rosa, <strong>meiner</strong> ist grün.","Diese Tiere sind <strong>meine</strong>.","Ich liebe mein Auto, aber <strong>deins</strong> ist schöner.","Sind alle diese Schuhe <strong>deine</strong>?","Dieser Karton ist <strong>deiner</strong>.","Alle diese Lutscher sind <strong>seine</strong>.","Ist dieses Werkzeug <strong>seins</strong>?","Ich glaube, dass dieser Stift <strong>seiner</strong> ist.","Ist diese Säge <strong>Ihre</strong>?","Sind diese Kleider <strong>Ihre</strong>?","Dieses Restaurant ist <strong>Ihres</strong>.","Diese Kamera ist <strong>ihre</strong>.","Diese Spielsachen sind <strong>ihre</strong>.","Der Computer ist <strong>ihrer</strong>."];var engExamples1 = ["This is <em>my pizza slice</em>. This is <em>mine</em>. (neuter noun)","Your hat is pink, <em>mine</em> is green. (masc. noun)","These animals are <em>mine</em>. (plural noun)","I love my car, but <em>yours</em> is prettier. (informal / neuter noun)","Are all these shoes <em>yours</em>? (informal / plural noun)","This package is <em>yours</em>. (informal / masc. noun)","All these lollipops are <em>his</em>. (plural noun)","Is this tool <em>his</em>? (neuter noun)","I believe that this pen is <em>his</em>. (masc. Noun)","Is this saw <em>yours</em>? (formal / fem. noun)","Are these clothes <em>yours</em>? (formal / plural noun)","This restaurant is <em>yours</em>. (formal / neuter noun)","This camera is <em>hers</em>. (fem. noun)","These toys are <em>hers</em>. (plural noun)","This computer is <em>hers</em>. (masc. noun)"];

var forExamples2 = ["Deine Katze ist grau, <strong>unsere</strong> ist weiß.","Dieser Staubsauger ist <strong>unserer</strong>.","Diese Äpfel sind <strong>unsere</strong>.","Mein Hemd ist rot. <strong>Eures</strong> ist blau.","Meine Katze ist schwarz und <strong>eure</strong> ist weiß.","Dieser Tisch ist <strong>eurer</strong>.","Unser Lieferwagen ist neu, <strong>ihrer</strong> ist alt.","Mein Gemälde ist modern, <strong>ihres</strong> ist antik.","Unser Land ist groß, aber <strong>ihres</strong> ist sehr groß.","Ist dieses Haus <strong>ihres</strong>?"];var engExamples2 = ["Your cat is grey, <em>ours</em> is white. (fem. noun)","This vacuum cleaner is <em>ours</em>. (masc. noun)","These apples are <em>ours</em>. (plural noun)","My shirt is red. <em>Yours</em> is blue. (plural ''your'' / neuter noun)","My cat is black and <em>yours</em> is white. (plural ''your'' / fem. noun)","This table is <em>yours</em>. (plural ''your'' / masc. noun)","Our truck is new, <em>theirs</em> is old. (masc. noun)","My painting is modern, <em>theirs</em> is antique. (neuter noun)","Our land is large, but <em>theirs</em> is very large. (neuter noun)","Is this house <em>theirs</em>? (neuter noun)"];